spring.application.name=user-service
server.port=9000

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://a7medselim123456_db_user:Lzc8xLgZvszQw1Xs@cluster0.37helqe.mongodb.net/hotel_users}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET:hotel_jwt_secret_key_2024_very_secure_random_string}
jwt.expiration=86400000
